port: 8080
max_clients: 2

#Player stats
player:
  #Speed
  move_speed: 0.02
  rot_speed: 0.02
  #Collider
  size: 0.2
  #Initial stats
  initial_health: 100
  initial_score: 0
  total_lives: 5
  has_key: 1 # 0 = false, otro numero = true
  initial_bullets: 10
  #Initial weapons
  weapons:
    initial_weapon: 1 # 0 = knife, 1 = pistol
    knife:
      time_between_stabs: 1
      range: 0.5
    chain_gun:
      time_between_shots: 0.1
    machine_gun:
      time_between_shots: 0.1
      time_between_bursts: 0.3
      bullets_per_burst: 5


max_health: &max_health_global 100

#Items
items:
  #Treasure
  cross:
    texture: 2
    value: 10
    radius: 0.5
  cup:
    texture: 3
    value: 15
    radius: 0.5
# chest:
# crown:
  #Health recover
  food:
    texture: 2
    value: 10
    radius: 0.4
    max_health: *max_health_global
  medical_kit:
    texture: 2
    value: 20
    radius: 0.2
    max_health: *max_health_global
  blood:
    texture: 2
    value: 1
    radius: 0.3
    max_health: 11
  #Otros
  #key:
#    texture: 3
#    value: 1
#    radius: 0.2
  #bullets/ammo:
#    texture: 4
#    value: 5
#    radius: 0.2

#    chain_gun:
#      texture: 4
#      value: 3 #value = id
#      radius: 0.3

