port: 8080
max_clients: 1

length: 5
width: 5
map:
  - [1, 1, 1, 1, 1]
  - [1, 0, 0, 0, 1]
  - [1, 0, 0, 0, 1]
  - [1, 0, 0, 0, 1]
  - [1, 1, 1, 1, 1]

player_1:
  pos_x: 2.0
  pos_y: 2.0
  dir_x: -1
  dir_y: 0
  move_speed: 0.02
  rot_speed: 0.02
  cam_plane_x: 0
  cam_plane_y: 1

player_2:
  pos_x: 3.0
  pos_y: 3.0
  dir_x: -1
  dir_y: 0
  move_speed: 0.02
  rot_speed: 0.02
  cam_plane_x: 0
  cam_plane_y: 1

initial_health: 100
initial_score: 0
total_lives: 3
has_key: 0 #0 = false, otro numero = true
initial_bullets: 10

