port: 8080
max_clients: 2

#Player stats
player:
  #Speed
  move_speed: 0.02
  rot_speed: 0.02
  #Collider
  size: 0.2
  #Initial stats
  initial_health: 100
  initial_score: 0
  total_lives: 5
  initial_weapon: 1 # 0 = kinfe, 1 = pistol
  has_key: 1 # 0 = false, otro numero = true
  initial_bullets: 10
#  initial_weapons: *global_initial_weapons

#Items
items:
  treasure:
    texture: 2
    value: 10
    radius: 0.5
  food:
    texture: 2
    value: 10
    radius: 0.4
  medical_kit:
    texture: 2
    value: 20
    radius: 0.2
  blood:
    texture: 2
    value: 1
    radius: 0.3
  #key:
#    texture: 3
#    value: 1
#    radius: 0.2
  #bullets/ammo:
#    texture: 4
#    value: 5
#    radius: 0.2

#weapons: