port: 8080
max_clients: 2

weapons:
  chain_gun:
    time_between_shots: &chain_gun_shots 0.1
  machine_gun:
    time_between_shots: &machine_gun_shots 0.1
    time_between_bursts: &machine_gun_bursts 0.3
    bullets_per_burst: &machine_gun_bullets 5

max_health: &max_health_global 100

#Player stats
player:
  #Speed
  move_speed: 0.02
  rot_speed: 0.02
  #Collider
  size: 0.2
  #Initial stats
  #Cambiar por numero en caso de ser necesario/para tests.
  initial_health: *max_health_global
  initial_score: 0
  total_lives: 5
  has_key: 1 # 0 = false, otro numero = true
  initial_bullets: 10
  #Initial weapons
  weapons:
    initial_weapon: 1 # 0 = knife, 1 = pistol
    knife:
      time_between_stabs: 1
      range: 0.5
    chain_gun:
      time_between_shots: *chain_gun_shots
    machine_gun:
      time_between_shots: *machine_gun_shots
      time_between_bursts: *machine_gun_bursts
      bullets_per_burst: *machine_gun_bullets

#Items
items:
  #Treasure
  cross:
    texture: 31
    value: 10
    radius: 0.5
  crown:
    texture: 32
    value: 200
    radius: 0.5
  cup:
    texture: 33
    value: 50
    radius: 0.5
  chest:
    texture: 34
    value: 100
    radius: 0.5

  #Health recover
  food:
    texture: 29
    value: 10
    radius: 0.4
    max_health: *max_health_global
  medical_kit:
    texture: 36
    value: 20
    radius: 0.2
    max_health: *max_health_global
  blood:
    texture: 27
    value: 1
    radius: 0.3
    max_health: 11
  #Otros
  key:
    texture: 37
    value: 1 #value = door?
    radius: 0.2
#  bullets/ammo:
#    texture: 4
#    value: 5
#    radius: 0.2
  #Weapons
  chain_gun:
    texture: 25
    value: 2 #value = id
    radius: 0.3
    time_between_shots: *chain_gun_shots
  machine_gun:
    texture: 24
    value: 3 #value = id
    radius: 0.3
    time_between_shots: *machine_gun_shots
    time_between_bursts: *machine_gun_bursts
    bullets_per_burst: *machine_gun_bullets
