port: 8080
tick_rate: 128
weapons_general:
  machine_gun:
    time_between_shots: &machine_gun_shots 0.1
    time_between_bursts: &machine_gun_bursts 0.3
    bullets_per_burst: &machine_gun_bullets 5
  chain_gun:
    time_between_shots: &chain_gun_shots 1
  rocket_launcher:
    move_speed: &rpg_move_speed 2.5
    size: &rpg_size 0.2
    max_damage: &rpg_max_damage 100
    max_damage_distance: &rpg_max_damage_distance 3

max_health: &max_health_global 100

#Player stats
player:
  #Speed
  move_speed: 2.5
  rot_speed: 2.5
  #Collider
  size: 0.2
  #Initial stats
  #Cambiar por numero en caso de ser necesario/para tests.
  initial_health: *max_health_global
  initial_score: 0
  total_lives: 5
  #Key
  key:
    radius: &key_radius 0.2
  #Initial weapons
  weapons:
    initial_weapon: 1 # 0 = knife, 1 = pistol
    bullet:
      initial_bullets: 100
      max_bullets: &max_bullets 100
      radius: &bullet_radius 0.2
    knife:
      time_between_stabs: 1
      range: 0.5
  bot_path: "../server_src/Bots/Destripador.lua"

#Items
items:
  #Treasure
  cross:
    value: 10
    radius: 0.5
  crown:
    value: 200
    radius: 0.5
  cup:
    value: 50
    radius: 0.5
  chest:
    value: 100
    radius: 0.5
  #Health recover
  food:
    value: 10
    radius: 0.4
    max_health: *max_health_global
  medical_kit:
    value: 20
    radius: 0.2
    max_health: *max_health_global
  blood:
    value: 1
    radius: 0.3
    max_health: 11
  #Otros
  key:
    radius: *key_radius
  bullet:
    value: 5
    radius: *bullet_radius
    max_bullets: *max_bullets
  #Weapons
  machine_gun:
    radius: 0.3
    time_between_shots: *machine_gun_shots
    time_between_bursts: *machine_gun_bursts
    bullets_per_burst: *machine_gun_bullets
  chain_gun:
    radius: 0.3
    time_between_shots: *chain_gun_shots
  rocket_launcher:
    radius: 0.3
    move_speed: *rpg_move_speed
    size: *rpg_size
    max_damage: *rpg_max_damage
    max_damage_distance: *rpg_max_damage_distance
